/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {
    @Test public void testAppHasAGreeting() {
    	assertTrue(true);
    }
}
